### ISSUE TITLE
Update gnome runtime to 3.38

### ISSUE THREAD

**Issue by soredake** [flathub/com.github.ztefn.haguichi#4]

**Comment by ztefn** [comment]
@soredake I have seen your earlier pull request and [asked some questions](https://github.com/flathub/com.github.ztefn.haguichi/pull/3#issuecomment-727237494). Can you answer them?

**Comment by soredake** [comment]
>Or wait until the first point release (3.38.1) is out?

Probably this, 3.38 already have two point releases.

![изображение](https://user-images.githubusercontent.com/5204968/103101801-f6001e00-4621-11eb-882e-c6d33db77803.png)

**Comment by ztefn** [comment]
Done. Thanks for your reply!
